// Code generated by admin:make-resource. Media reports are an all-user admin
// moderation queue; member submission stays on the dedicated API route.
export const resourceDefinition = {
  name: 'reports',
  label: 'Media reports',
  route: '/reports',
  permission: 'admin.reports.view',
  icon: 'flag',
  pageMode: 'generic',
  navigation: { group: 'moderation', order: 10 },
  dataScope: 'all',
  actions: [
    { name: 'view', label: 'View', kind: '', permission: 'admin.reports.view', batch: false, payload: '' },
    { name: 'resolve', label: 'Resolve report', kind: 'report-resolve', permission: 'admin.reports.update', batch: true, payload: 'report-resolve', payload_fields: [{ name: 'action', label: 'Resolution action', type: 'select', required: true, options: [{ value: 'dismiss', label: 'Dismiss report' }, { value: 'hide_media', label: 'Hide media' }, { value: 'restore_media', label: 'Restore media' }] }, { name: 'resolution', label: 'Resolution note', type: 'textarea', required: true }] },
  ],
  relations: [], form_groups: [], details: [],
  fields: [
    { name: 'media_asset_id', label: 'Media ID', type: 'integer', visible: true, readable: true, writable: false, sensitive: false },
    { name: 'reporter_id', label: 'Reporter ID', type: 'integer', visible: true, readable: true, writable: false, sensitive: false },
    { name: 'reason', label: 'Reason', type: 'text', visible: true, readable: true, writable: false, sensitive: false },
    { name: 'description', label: 'Description', type: 'textarea', visible: true, readable: true, writable: false, sensitive: false },
    { name: 'status', label: 'Status', type: 'select', visible: true, readable: true, writable: false, sensitive: false, options: [{ value: 'pending', label: 'Pending' }, { value: 'in_review', label: 'In review' }, { value: 'resolved', label: 'Resolved' }, { value: 'rejected', label: 'Rejected' }] },
    { name: 'resolution', label: 'Resolution', type: 'textarea', visible: true, readable: true, writable: false, sensitive: false },
    { name: 'resolved_by', label: 'Resolved by', type: 'integer', visible: true, readable: true, writable: false, sensitive: false },
    { name: 'resolved_at', label: 'Resolved at', type: 'datetime-local', visible: true, readable: true, writable: false, sensitive: false },
  ],
} as const
