<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Link2, Plus, Save, Trash2 } from '@lucide/vue'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Checkbox } from '@/components/ui/checkbox'
import { Field, FieldGroup, FieldLabel } from '@/components/ui/field'
import { Input } from '@/components/ui/input'
import { ApiError, errorMessageKey } from '@/lib/api'
import { footerApi, type NavigationGroupResult, type NavigationItem } from '@/modules/footer-navigation/api'
import { useAuthStore } from '@/stores/auth'
import { useI18n } from 'vue-i18n'

const { t } = useI18n()
const auth = useAuthStore()
const groups = ref<NavigationGroupResult[]>([])
const loading = ref(true)
const saving = ref(false)
const error = ref('')
const groupForm = reactive({ id: 0, title: '', locale: 'all', sort_order: 0, is_enabled: true })
const itemForm = reactive({ id: 0, group_id: 0, parent_id: null as number | null, label: '', target_type: 'page' as NavigationItem['target_type'], target_value: '', open_in_new_tab: false, sort_order: 0, is_enabled: true })

function localError(value: unknown) { return value instanceof ApiError ? t(errorMessageKey(value.code)) : t('footerNavigation.saveFailed') }
async function load() { if (!auth.token) return; loading.value = true; try { groups.value = await footerApi.list(auth.token) } catch (value) { error.value = localError(value) } finally { loading.value = false } }
function editGroup(value: NavigationGroupResult['group']) { Object.assign(groupForm, value) }
function editItem(value: NavigationItem) { Object.assign(itemForm, value, { parent_id: value.parent_id ?? null }) }
function resetGroup() { Object.assign(groupForm, { id: 0, title: '', locale: 'all', sort_order: 0, is_enabled: true }) }
function resetItem(groupID = 0) { Object.assign(itemForm, { id: 0, group_id: groupID, parent_id: null, label: '', target_type: 'page', target_value: '', open_in_new_tab: false, sort_order: 0, is_enabled: true }) }
async function saveGroup() { if (!auth.token) return; saving.value = true; try { const input = { title: groupForm.title, locale: groupForm.locale, sort_order: groupForm.sort_order, is_enabled: groupForm.is_enabled }; groupForm.id ? await footerApi.updateGroup(groupForm.id, input, auth.token) : await footerApi.createGroup(input, auth.token); resetGroup(); await load() } catch (value) { error.value = localError(value) } finally { saving.value = false } }
async function saveItem() { if (!auth.token) return; saving.value = true; try { const input = { group_id: itemForm.group_id, parent_id: itemForm.parent_id || null, label: itemForm.label, target_type: itemForm.target_type, target_value: itemForm.target_value, open_in_new_tab: itemForm.open_in_new_tab, sort_order: itemForm.sort_order, is_enabled: itemForm.is_enabled }; itemForm.id ? await footerApi.updateItem(itemForm.id, input, auth.token) : await footerApi.createItem(input, auth.token); resetItem(itemForm.group_id); await load() } catch (value) { error.value = localError(value) } finally { saving.value = false } }
async function removeGroup(id: number) { if (!auth.token || !window.confirm(t('footerNavigation.confirmDeleteGroup'))) return; await footerApi.deleteGroup(id, auth.token); await load() }
async function removeItem(id: number) { if (!auth.token || !window.confirm(t('footerNavigation.confirmDeleteItem'))) return; await footerApi.deleteItem(id, auth.token); await load() }
onMounted(load)
</script>

<template>
  <div class="flex flex-col gap-6">
    <div class="flex items-center gap-3"><Link2 class="size-5 text-primary" /><div><h1 class="text-2xl font-semibold tracking-tight">{{ t('footerNavigation.title') }}</h1><p class="mt-1 text-sm text-muted-foreground">{{ t('footerNavigation.description') }}</p></div></div>
    <Alert v-if="error" variant="destructive"><AlertTitle>{{ t('states.errorTitle') }}</AlertTitle><AlertDescription>{{ error }}</AlertDescription></Alert>
    <Card><CardHeader><CardTitle>{{ t('footerNavigation.groupForm') }}</CardTitle><CardDescription>{{ t('footerNavigation.groupFormDescription') }}</CardDescription></CardHeader><CardContent><form class="grid gap-4 md:grid-cols-4" @submit.prevent="saveGroup"><Field><FieldLabel for="footer-group-title">{{ t('footerNavigation.groupTitle') }}</FieldLabel><Input id="footer-group-title" v-model="groupForm.title" required /></Field><Field><FieldLabel for="footer-group-locale">{{ t('footerNavigation.locale') }}</FieldLabel><Input id="footer-group-locale" v-model="groupForm.locale" /></Field><Field><FieldLabel for="footer-group-order">{{ t('footerNavigation.sortOrder') }}</FieldLabel><Input id="footer-group-order" v-model.number="groupForm.sort_order" type="number" /></Field><div class="flex items-end gap-2"><label class="flex min-h-9 items-center gap-2 text-sm"><Checkbox :model-value="groupForm.is_enabled" @update:model-value="groupForm.is_enabled = Boolean($event)" />{{ t('footerNavigation.enabled') }}</label><Button type="submit" :disabled="saving"><Save data-icon="inline-start" />{{ groupForm.id ? t('resource.save') : t('footerNavigation.addGroup') }}</Button><Button v-if="groupForm.id" type="button" variant="ghost" @click="resetGroup">{{ t('resource.cancel') }}</Button></div></form></CardContent></Card>
    <Card><CardHeader><CardTitle>{{ t('footerNavigation.itemForm') }}</CardTitle><CardDescription>{{ t('footerNavigation.itemFormDescription') }}</CardDescription></CardHeader><CardContent><form class="grid gap-4 md:grid-cols-4" @submit.prevent="saveItem"><Field><FieldLabel for="footer-item-group">{{ t('footerNavigation.group') }}</FieldLabel><select id="footer-item-group" v-model.number="itemForm.group_id" class="h-9 w-full rounded-lg border bg-background px-2 text-sm" required><option :value="0" disabled>{{ t('footerNavigation.chooseGroup') }}</option><option v-for="entry in groups" :key="entry.group.id" :value="entry.group.id">{{ entry.group.title }}</option></select></Field><Field><FieldLabel for="footer-item-parent">{{ t('footerNavigation.parent') }}</FieldLabel><select id="footer-item-parent" v-model="itemForm.parent_id" class="h-9 w-full rounded-lg border bg-background px-2 text-sm"><option :value="null">{{ t('footerNavigation.topLevel') }}</option><option v-for="item in groups.find((entry) => entry.group.id === itemForm.group_id)?.items || []" :key="item.id" :value="item.id">{{ item.label }}</option></select></Field><Field><FieldLabel for="footer-item-label">{{ t('footerNavigation.itemLabel') }}</FieldLabel><Input id="footer-item-label" v-model="itemForm.label" required /></Field><Field><FieldLabel for="footer-item-type">{{ t('footerNavigation.targetType') }}</FieldLabel><select id="footer-item-type" v-model="itemForm.target_type" class="h-9 w-full rounded-lg border bg-background px-2 text-sm"><option value="page">{{ t('footerNavigation.targetPage') }}</option><option value="route">{{ t('footerNavigation.targetRoute') }}</option><option value="external">{{ t('footerNavigation.targetExternal') }}</option><option value="friends">{{ t('footerNavigation.targetFriends') }}</option></select></Field><Field class="md:col-span-2"><FieldLabel for="footer-item-value">{{ t('footerNavigation.targetValue') }}</FieldLabel><Input id="footer-item-value" v-model="itemForm.target_value" required /><p class="text-xs text-muted-foreground">{{ t('footerNavigation.targetHint') }}</p></Field><Field><FieldLabel for="footer-item-order">{{ t('footerNavigation.sortOrder') }}</FieldLabel><Input id="footer-item-order" v-model.number="itemForm.sort_order" type="number" /></Field><div class="flex items-end gap-2"><label class="flex min-h-9 items-center gap-2 text-sm"><Checkbox :model-value="itemForm.is_enabled" @update:model-value="itemForm.is_enabled = Boolean($event)" />{{ t('footerNavigation.enabled') }}</label><Button type="submit" :disabled="saving"><Plus data-icon="inline-start" />{{ itemForm.id ? t('resource.save') : t('footerNavigation.addItem') }}</Button></div></form></CardContent></Card>
    <div v-if="loading" class="text-sm text-muted-foreground">{{ t('resource.loading') }}</div>
    <div v-else class="grid gap-4"> <Card v-for="entry in groups" :key="entry.group.id"><CardHeader class="flex flex-row items-center justify-between"><div><CardTitle>{{ entry.group.title }}</CardTitle><CardDescription>{{ entry.group.locale }} · {{ entry.group.is_enabled ? t('footerNavigation.enabled') : t('footerNavigation.disabled') }}</CardDescription></div><div class="flex gap-2"><Button variant="outline" size="sm" @click="editGroup(entry.group)">{{ t('content.edit') }}</Button><Button variant="ghost" size="icon" @click="removeGroup(entry.group.id)"><Trash2 class="size-4" /></Button></div></CardHeader><CardContent><div v-if="!entry.items.length" class="text-sm text-muted-foreground">{{ t('footerNavigation.noItems') }}</div><div v-else class="divide-y rounded-md border"><div v-for="item in entry.items" :key="item.id" class="flex items-center justify-between gap-3 p-3"><div class="min-w-0"><p class="font-medium">{{ item.parent_id ? '↳ ' : '' }}{{ item.label }}</p><p class="truncate text-xs text-muted-foreground">{{ item.target_type }}: {{ item.target_value }}</p></div><div class="flex gap-2"><Button variant="ghost" size="sm" @click="editItem(item)">{{ t('content.edit') }}</Button><Button variant="ghost" size="icon" @click="removeItem(item.id)"><Trash2 class="size-4" /></Button></div></div></div></CardContent></Card></div>
  </div>
</template>
