// Code generated by admin:make-resource. DO NOT EDIT.
package advertising

import "testing"

func TestManifestHasResourceIdentity(t *testing.T) {
	manifest := Manifest()
	if manifest.Name != "advertising" || manifest.Route != "/admin/advertising" {
		t.Fatalf("unexpected manifest: %+v", manifest)
	}
}

func TestManifestUsesTheFourSimpleAdPlacements(t *testing.T) {
	manifest := Manifest()
	var placementOptions []string
	for _, field := range manifest.Fields {
		if field.Name != "placement" {
			continue
		}
		for _, option := range field.Options {
			placementOptions = append(placementOptions, option.Value)
		}
	}
	want := []string{"header", "footer", "left", "right"}
	if len(placementOptions) != len(want) {
		t.Fatalf("placement options = %v, want %v", placementOptions, want)
	}
	for index, value := range want {
		if placementOptions[index] != value {
			t.Fatalf("placement options = %v, want %v", placementOptions, want)
		}
	}
}

func TestManifestExposesAdminCreativeTypesAndContent(t *testing.T) {
	manifest := Manifest()
	fields := map[string]struct {
		fieldType string
		options   []string
	}{}
	for _, field := range manifest.Fields {
		var options []string
		for _, option := range field.Options {
			options = append(options, option.Value)
		}
		fields[field.Name] = struct {
			fieldType string
			options   []string
		}{field.Type, options}
	}

	creativeType, ok := fields["creative_type"]
	if !ok || creativeType.fieldType != "select" {
		t.Fatalf("creative_type field = %+v, want select", creativeType)
	}
	wantTypes := []string{"text", "image", "script"}
	if len(creativeType.options) != len(wantTypes) {
		t.Fatalf("creative_type options = %v, want %v", creativeType.options, wantTypes)
	}
	for index, value := range wantTypes {
		if creativeType.options[index] != value {
			t.Fatalf("creative_type options = %v, want %v", creativeType.options, wantTypes)
		}
	}
	if content, ok := fields["creative_content"]; !ok || content.fieldType != "textarea" {
		t.Fatalf("creative_content field = %+v, want textarea", content)
	}
	for _, field := range Manifest().Fields {
		if field.Name == "creative_content" && field.Hint == "" {
			t.Fatal("creative_content must explain where text, image URL, and JavaScript source go")
		}
	}
}

func TestManifestDoesNotRenderFullCreativeContentInAdminList(t *testing.T) {
	for _, column := range Manifest().Columns {
		if column.Name == "creative_content" {
			t.Fatal("creative_content must stay in the edit form, not be rendered in the admin list")
		}
	}
}
