// Code generated by admin:make-resource. DO NOT EDIT.
package advertising

import (
	"goravel/app/core/resource"
	advertisingservices "goravel/app/services/advertising"
)

func Manifest() resource.Manifest {
	return resource.Manifest{
		Name: "advertising", Label: "Advertising", Route: "/admin/advertising", Table: "advertising", Permissions: []string{"admin.advertising.view"}, Navigation: resource.Navigation{Group: "business", Order: 100},

		WritePreparer: advertisingservices.PrepareAdvertisingWrite,
		Fields: []resource.Field{
			{Name: "name", Label: "Name", Type: "text", Required: true, Visible: true, Readable: true, Writable: true, Sensitive: false, PolicyConfigured: true},
			{Name: "placement", Label: "Placement", Type: "select", Required: true, Visible: true, Readable: true, Writable: true, Sensitive: false, PolicyConfigured: true, Options: []resource.Option{{Value: "header", Label: "Header"}, {Value: "footer", Label: "Footer"}, {Value: "left", Label: "Left sidebar"}, {Value: "right", Label: "Right sidebar"}}},
			{Name: "creative_type", Label: "Creative type", Type: "select", Required: true, Visible: true, Readable: true, Writable: true, Sensitive: false, PolicyConfigured: true, Options: []resource.Option{{Value: "text", Label: "Text"}, {Value: "image", Label: "Image"}, {Value: "script", Label: "JavaScript"}}},
			{Name: "creative_content", Label: "Creative content", Type: "textarea", Hint: "Enter text, an image URL, plain JavaScript, or a complete embed from any ad provider. Complete HTML embeds run in an isolated iframe.", Required: true, Visible: true, Readable: true, Writable: true, Sensitive: false, PolicyConfigured: true},
			{Name: "target_url", Label: "Target_url", Type: "text", Required: false, Visible: true, Readable: true, Writable: true, Sensitive: false, PolicyConfigured: true},
			{Name: "plan_code", Label: "Plan_code", Type: "text", Required: false, Visible: true, Readable: true, Writable: true, Sensitive: false, PolicyConfigured: true},
			{Name: "starts_at", Label: "Starts_at", Type: "datetime-local", Required: false, Visible: true, Readable: true, Writable: true, Sensitive: false, PolicyConfigured: true},
			{Name: "ends_at", Label: "Ends_at", Type: "datetime-local", Required: false, Visible: true, Readable: true, Writable: true, Sensitive: false, PolicyConfigured: true},
			{Name: "status", Label: "Status", Type: "select", Required: true, Visible: true, Readable: true, Writable: true, Sensitive: false, PolicyConfigured: true, Options: []resource.Option{{Value: "active", Label: "Active"}, {Value: "disabled", Label: "Disabled"}}},
		},
		Columns: []resource.Column{
			{Name: "name", Label: "Name", Sortable: true},
			{Name: "placement", Label: "Placement", Sortable: true},
			{Name: "creative_type", Label: "Creative type", Sortable: true},
			{Name: "creative_content", Label: "Creative content", Sortable: false},
			{Name: "target_url", Label: "Target_url", Sortable: true},
			{Name: "plan_code", Label: "Plan_code", Sortable: true},
			{Name: "starts_at", Label: "Starts_at", Sortable: true},
			{Name: "ends_at", Label: "Ends_at", Sortable: true},
			{Name: "status", Label: "Status", Sortable: true},
		},
		Actions: []resource.Action{
			{Name: "view", Label: "View", Kind: "", Permission: "admin.advertising.view", Batch: false, Payload: ""},
			{Name: "create", Label: "Create", Kind: "", Permission: "admin.advertising.create", Batch: false, Payload: ""},
			{Name: "update", Label: "Update", Kind: "", Permission: "admin.advertising.update", Batch: false, Payload: ""},
			{Name: "delete", Label: "Delete", Kind: "", Permission: "admin.advertising.delete", Batch: false, Payload: ""},
		},
		Relations:  []resource.Relation{},
		FormGroups: []resource.FormGroup{},
		Details:    []resource.DetailSection{},
	}
}
