// Code generated by admin:make-resource. DO NOT EDIT.
package advertising

import "github.com/goravel/framework/database/orm"

type Advertising struct {
	orm.Model
	Name            string `json:"name"`
	Placement       string `json:"placement"`
	CreativeUrl     string `json:"creative_url"`
	CreativeType    string `json:"creative_type"`
	CreativeContent string `json:"creative_content"`
	TargetUrl       string `json:"target_url"`
	PlanCode        string `json:"plan_code"`
	StartsAt        string `json:"starts_at"`
	EndsAt          string `json:"ends_at"`
	Status          string `json:"status"`
}
