// Code generated by admin:make-resource. DO NOT EDIT.
export const resourceDefinition = {
  name: "advertising",
  label: "Advertising",
  route: "/advertising",
  permission: "admin.advertising.view",
  icon: "box",
  pageMode: "generic",
  navigation: { group: "business", order: 100 },

  actions: [{ name: "view", label: "View", kind: "", permission: "admin.advertising.view", batch: false, payload: "" }, { name: "create", label: "Create", kind: "", permission: "admin.advertising.create", batch: false, payload: "" }, { name: "update", label: "Update", kind: "", permission: "admin.advertising.update", batch: false, payload: "" }, { name: "delete", label: "Delete", kind: "", permission: "admin.advertising.delete", batch: false, payload: "" }],
  relations: [],
  form_groups: [],
  details: [],
  fields: [{ name: "name", label: "Name", type: "text", required: true, visible: true, readable: true, writable: true, sensitive: false }, { name: "placement", label: "Placement", type: "select", required: true, visible: true, readable: true, writable: true, sensitive: false, options: [{ value: "header", label: "Header" }, { value: "footer", label: "Footer" }, { value: "left", label: "Left sidebar" }, { value: "right", label: "Right sidebar" }] }, { name: "creative_type", label: "Creative type", type: "select", required: true, visible: true, readable: true, writable: true, sensitive: false, options: [{ value: "text", label: "Text" }, { value: "image", label: "Image" }, { value: "script", label: "JavaScript" }] }, { name: "creative_content", label: "Creative content", type: "textarea", required: true, visible: true, readable: true, writable: true, sensitive: false }, { name: "target_url", label: "Target_url", type: "text", required: false, visible: true, readable: true, writable: true, sensitive: false }, { name: "plan_code", label: "Plan_code", type: "text", required: false, visible: true, readable: true, writable: true, sensitive: false }, { name: "starts_at", label: "Starts_at", type: "datetime-local", required: false, visible: true, readable: true, writable: true, sensitive: false }, { name: "ends_at", label: "Ends_at", type: "datetime-local", required: false, visible: true, readable: true, writable: true, sensitive: false }, { name: "status", label: "Status", type: "select", required: true, visible: true, readable: true, writable: true, sensitive: false, options: [{ value: "active", label: "Active" }, { value: "disabled", label: "Disabled" }] }],
} as const;
