import assert from 'node:assert/strict'
import fs from 'node:fs'

const router = fs.readFileSync(new URL('../src/router/index.ts', import.meta.url), 'utf8')
const plans = fs.readFileSync(new URL('../src/modules/member/pages/MemberPlansPage.vue', import.meta.url), 'utf8')
const billingApi = fs.readFileSync(new URL('../src/modules/billing/api.ts', import.meta.url), 'utf8')
const memberShell = fs.readFileSync(new URL('../src/core/layouts/MemberShell.vue', import.meta.url), 'utf8')
const checkout = fs.readFileSync(new URL('../src/modules/member/pages/MemberCheckoutPage.vue', import.meta.url), 'utf8')

const memberRoutes = fs.readFileSync(new URL('../src/apps/member/route-private.ts', import.meta.url), 'utf8')
assert.match(memberRoutes, /path:\s*'checkout\/:orderId'/, 'member checkout route is missing')
assert.match(memberRoutes, /path:\s*'orders'/, 'member orders route is missing')
assert.match(memberRoutes, /path:\s*'orders\/:id'/, 'member order detail route is missing')
assert.match(memberRoutes, /name:\s*'member-checkout'/)
assert.match(memberRoutes, /name:\s*'member-orders'/)
assert.match(memberRoutes, /name:\s*'member-order-detail'/)
assert.ok(billingApi.includes("/api/v1/orders"), 'billing API must start server-priced checkout')
assert.ok(billingApi.includes('/cancel'), 'billing API must support canceling unpaid orders')
assert.ok(billingApi.includes('/payments/fake/succeed'), 'billing API must expose the development success path')
assert.ok(memberShell.includes("member.nav.orders"), 'member navigation must expose own orders')
assert.ok(checkout.includes('completeFakeMemberPayment'), 'checkout must expose the development gateway action')
assert.ok(checkout.includes('cancelMemberOrder'), 'checkout must allow canceling unpaid orders')
assert.ok(checkout.includes("error.value = 'order'"), 'checkout must identify order loading failures')
assert.ok(checkout.includes("error.value = 'gateway'"), 'checkout must keep gateway loading failures separate from order failures')
assert.ok(checkout.includes('gatewayErrorDescription'), 'checkout must explain unavailable payment channels')
assert.ok(plans.includes('free'), 'plans page must retain a Free branch')
console.log('billing-ui tests: PASS')
