// Code generated by admin:make-resource. DO NOT EDIT.
export const resourceDefinition = {
  name: "albums",
  label: "Albums",
  route: "/albums",
  permission: "admin.albums.view",
  icon: "box",
  pageMode: "generic",
  navigation: { group: "business", order: 100 },
  dataScope: "all",
  ownerField: "user_id",

  actions: [{ name: "view", label: "View", kind: "", permission: "admin.albums.view", batch: false, payload: "" }, { name: "create", label: "Create", kind: "", permission: "admin.albums.create", batch: false, payload: "" }, { name: "update", label: "Update", kind: "", permission: "admin.albums.update", batch: false, payload: "" }, { name: "delete", label: "Delete", kind: "", permission: "admin.albums.delete", batch: false, payload: "" }],
  relations: [],
  form_groups: [],
  details: [],
  fields: [{ name: "name", label: "Name", type: "text", required: true, visible: true, readable: true, writable: true, sensitive: false }, { name: "cover_media_id", label: "Cover_media_id", type: "integer", required: false, visible: false, readable: false, writable: false, sensitive: false }, { name: "visibility", label: "Visibility", type: "select", required: true, visible: true, readable: true, writable: true, sensitive: false, options: [{ value: "private", label: "Private" }, { value: "link", label: "Link" }, { value: "public", label: "Public" }] }, { name: "user_id", label: "User_id", type: "integer", required: false, visible: false, readable: false, writable: false, sensitive: false }],
} as const;
