// Code generated by admin:make-resource. DO NOT EDIT.
package permissions

const (
	AdvertisingView   = "admin.advertising.view"
	AdvertisingCreate = "admin.advertising.create"
	AdvertisingUpdate = "admin.advertising.update"
	AdvertisingDelete = "admin.advertising.delete"
)

var All = []string{AdvertisingView, AdvertisingCreate, AdvertisingUpdate, AdvertisingDelete}
