// Code generated by admin:make-resource. DO NOT EDIT.
package permissions

const (
	FoldersView   = "admin.folders.view"
	FoldersCreate = "admin.folders.create"
	FoldersUpdate = "admin.folders.update"
	FoldersDelete = "admin.folders.delete"
)

var All = []string{FoldersView, FoldersCreate, FoldersUpdate, FoldersDelete}
