import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import publicPages from '../src/apps/member/public-pages.json' with { type: 'json' }

const root = dirname(fileURLToPath(import.meta.url))
const dist = join(root, '..', 'dist')
const template = (await readFile(join(dist, 'index.html'), 'utf8'))
  // Make repeated SSG builds idempotent even when dist/index.html was itself
  // generated by an earlier run.
  .replace(/<div id="app"[^>]*>[\s\S]*?<\/div>/i, '<div id="app"></div>')
const origin = process.env.SSG_PUBLIC_ORIGIN || 'https://img.example.com'

const albumIDs = String(process.env.SSG_PUBLIC_ALBUM_IDS || '')
  .split(',')
  .map((value) => value.trim())
  .filter((value) => /^\d+$/.test(value))
const apiOrigin = (process.env.SSG_API_ORIGIN || 'http://127.0.0.1:53085').replace(/\/$/, '')

function renderNode(node) {
  if (!node || typeof node !== 'object') return ''
  const children = Array.isArray(node.content) ? node.content.map(renderNode).join('') : ''
  if (node.type === 'text') return escapeHTML(node.text || '')
  if (node.type === 'doc') return children
  if (node.type === 'paragraph') return `<p>${children}</p>`
  if (node.type === 'heading') {
    const level = Math.min(6, Math.max(1, Number(node.attrs?.level || 2)))
    return `<h${level}>${children}</h${level}>`
  }
  if (node.type === 'bulletList') return `<ul>${children}</ul>`
  if (node.type === 'orderedList') return `<ol>${children}</ol>`
  if (node.type === 'listItem') return `<li>${children}</li>`
  if (node.type === 'blockquote') return `<blockquote>${children}</blockquote>`
  if (node.type === 'hardBreak') return '<br>'
  if (node.type === 'horizontalRule') return '<hr>'
  return children
}

async function enrichPublishedPage(page) {
  if (!page.path.startsWith('/page/')) return page
  try {
    const slug = page.path.slice('/page/'.length)
    const response = await fetch(`${apiOrigin}/api/v1/site/pages/${encodeURIComponent(slug)}`)
    if (!response.ok) return page
    const payload = await response.json()
    const published = payload?.data
    if (!published) return page
    return {
      ...page,
      title: published.seo_title || published.title || page.title,
      description: published.seo_description || published.excerpt || page.description,
      heading: published.title || page.heading,
      contentHTML: published.content ? renderNode(published.content) : undefined,
    }
  } catch (error) {
    console.warn(`Using fallback SEO copy for ${page.path}: ${error instanceof Error ? error.message : String(error)}`)
    return page
  }
}

const albumPages = []
for (const id of albumIDs) {
  try {
    const response = await fetch(`${apiOrigin}/api/v1/public/albums/${id}`)
    if (!response.ok) continue
    const payload = await response.json()
    const album = payload?.data
    if (!album || album.visibility !== 'public') continue
    albumPages.push({
      path: `/a/${id}`,
      title: `${album.name} — FastImg`,
      description: `Browse the public album “${album.name}” on FastImg.`,
      heading: album.name,
      body: `Public images from the ${album.name} album.`,
      album,
    })
  } catch (error) {
    console.warn(`Skipped public album ${id}: ${error instanceof Error ? error.message : String(error)}`)
  }
}

const pages = [...await Promise.all(publicPages.map(enrichPublishedPage)), ...albumPages]

function escapeHTML(value) {
  return String(value).replace(/[&<>"']/g, (character) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  })[character])
}

function safeJSON(value) {
  return JSON.stringify(value).replace(/</g, '\\u003c').replace(/>/g, '\\u003e').replace(/&/g, '\\u0026')
}

function replaceOrAppend(document, pattern, value) {
  if (pattern.test(document)) return document.replace(pattern, value)
  return document.replace('</head>', `${value}</head>`)
}

for (const page of pages) {
  const canonical = `${origin.replace(/\/$/, '')}${page.path}`
  const tags = [
    [`<title[^>]*>[\\s\\S]*?<\\/title>`, `<title>${escapeHTML(page.title)}</title>`],
    [`<meta\\s+name="description"[^>]*>`, `<meta name="description" content="${escapeHTML(page.description)}">`],
    [`<meta\\s+property="og:title"[^>]*>`, `<meta property="og:title" content="${escapeHTML(page.title)}">`],
    [`<meta\\s+property="og:description"[^>]*>`, `<meta property="og:description" content="${escapeHTML(page.description)}">`],
    [`<meta\\s+property="og:type"[^>]*>`, '<meta property="og:type" content="website">'],
    [`<meta\\s+property="og:url"[^>]*>`, `<meta property="og:url" content="${escapeHTML(canonical)}">`],
    [`<link\\s+rel="canonical"[^>]*>`, `<link rel="canonical" href="${escapeHTML(canonical)}">`],
    [`<script\\s+type="application/ld\\+json">[\\s\\S]*?<\\/script>`, `<script type="application/ld+json">${safeJSON({ '@context': 'https://schema.org', '@type': 'WebSite', name: 'FastImg', url: origin })}</script>`],
  ]
  const albumContent = page.album?.media?.map((item) => `<article><a href="${escapeHTML(item.original_url)}"><img src="${escapeHTML(item.thumbnail_url)}" alt="${escapeHTML(item.original_name)}" loading="lazy"></a><p>${escapeHTML(item.original_name)}</p></article>`).join('') || ''
  const pageHTML = page.contentHTML || `<p>${escapeHTML(page.body)}</p>`
  const headingHTML = page.contentHTML ? '' : `<h1>${escapeHTML(page.heading)}</h1>`
  const content = page.album
    ? `<main data-fastimg-ssg="true"><h1>${escapeHTML(page.heading)}</h1><p>${escapeHTML(page.body)}</p><section>${albumContent}</section><p><a href="/discover">Discover more public images</a></p></main>`
    : `<main data-fastimg-ssg="true">${headingHTML}${pageHTML}<p><a href="/login">Sign in to upload</a> · <a href="/plans">View plans</a></p></main>`
  const mount = `<div id="app" data-fastimg-ssg="true">${content}</div>`
  let output = template
  for (const [pattern, tag] of tags) output = replaceOrAppend(output, new RegExp(pattern, 'i'), tag)
  output = output.replace('<div id="app"></div>', mount)
  const target = page.path === '/' ? join(dist, 'index.html') : join(dist, page.path.slice(1), 'index.html')
  await mkdir(dirname(target), { recursive: true })
  await writeFile(target, output)
}

console.log(`Generated SEO entry pages: ${pages.map((page) => page.path).join(', ')}`)
