// Code generated by admin:make-resource. DO NOT EDIT.
package permissions

const (
	AlbumsView   = "admin.albums.view"
	AlbumsCreate = "admin.albums.create"
	AlbumsUpdate = "admin.albums.update"
	AlbumsDelete = "admin.albums.delete"
)

var All = []string{AlbumsView, AlbumsCreate, AlbumsUpdate, AlbumsDelete}
