// Code generated by admin:make-resource. DO NOT EDIT.
package albums

import "testing"

func TestManifestHasResourceIdentity(t *testing.T) {
	manifest := Manifest()
	if manifest.Name != "albums" || manifest.Route != "/admin/albums" {
		t.Fatalf("unexpected manifest: %+v", manifest)
	}
	if string(manifest.DataScope) != "all" {
		t.Fatalf("admin albums must be all-scope, got %q", manifest.DataScope)
	}
}
