// Code generated by admin:make-resource. DO NOT EDIT.
package albums

import "goravel/app/core/resource"

func Manifest() resource.Manifest {
	return resource.Manifest{
		Name: "albums", Label: "Albums", Route: "/admin/albums", Table: "albums", Permissions: []string{"admin.albums.view"}, Navigation: resource.Navigation{Group: "business", Order: 100},
		DataScope: resource.DataScopeAll, OwnerField: "user_id",

		Fields: []resource.Field{
			{Name: "name", Label: "Name", Type: "text", Required: true, Visible: true, Readable: true, Writable: true, Sensitive: false, PolicyConfigured: true},
			{Name: "cover_media_id", Label: "Cover_media_id", Type: "integer", Required: false, Visible: false, Readable: false, Writable: false, Sensitive: false, PolicyConfigured: true},
			{Name: "visibility", Label: "Visibility", Type: "select", Required: true, Visible: true, Readable: true, Writable: true, Sensitive: false, PolicyConfigured: true, Options: []resource.Option{{Value: "private", Label: "Private"}, {Value: "link", Label: "Link"}, {Value: "public", Label: "Public"}}},
			{Name: "user_id", Label: "User_id", Type: "integer", Required: false, Visible: false, Readable: false, Writable: false, Sensitive: false, PolicyConfigured: true},
		},
		Columns: []resource.Column{
			{Name: "name", Label: "Name", Sortable: true},
			{Name: "cover_media_id", Label: "Cover_media_id", Sortable: true},
			{Name: "visibility", Label: "Visibility", Sortable: true},
			{Name: "user_id", Label: "User_id", Sortable: true},
		},
		Actions: []resource.Action{
			{Name: "view", Label: "View", Kind: "", Permission: "admin.albums.view", Batch: false, Payload: ""},
			{Name: "create", Label: "Create", Kind: "", Permission: "admin.albums.create", Batch: false, Payload: ""},
			{Name: "update", Label: "Update", Kind: "", Permission: "admin.albums.update", Batch: false, Payload: ""},
			{Name: "delete", Label: "Delete", Kind: "", Permission: "admin.albums.delete", Batch: false, Payload: ""},
		},
		Relations:  []resource.Relation{},
		FormGroups: []resource.FormGroup{},
		Details:    []resource.DetailSection{},
	}
}
