// Code generated by admin:make-resource. DO NOT EDIT.
package albums

import "github.com/goravel/framework/database/orm"

type Albums struct {
	orm.Model
	Name         string `json:"name"`
	CoverMediaId int    `json:"cover_media_id"`
	Visibility   string `json:"visibility"`
	UserId       int    `json:"user_id"`
}
