// Code generated by admin:make-resource. DO NOT EDIT.
package migrations

import (
	"github.com/goravel/framework/contracts/database/schema"

	"goravel/app/facades"
	"goravel/app/models"
)

type MfoldersCreateFoldersTable struct{}

func (m *MfoldersCreateFoldersTable) Signature() string {
	return "create_folders_table"
}

func (m *MfoldersCreateFoldersTable) Up() error {
	if err := facades.Schema().Create("folders", func(table schema.Blueprint) {
		table.ID()
		table.String("name")
		table.Integer("parent_id").Nullable()
		table.Integer("user_id")
		table.DateTimeTz("created_at").Nullable()
		table.DateTimeTz("updated_at").Nullable()
	}); err != nil {
		return err
	}
	for _, permission := range []models.Permission{
		{Name: "admin.folders.view", DisplayName: "Folders.view"},
		{Name: "admin.folders.create", DisplayName: "Folders.create"},
		{Name: "admin.folders.update", DisplayName: "Folders.update"},
		{Name: "admin.folders.delete", DisplayName: "Folders.delete"},
	} {
		exists, err := facades.Orm().Query().Model(&models.Permission{}).Where("name = ?", permission.Name).Exists()
		if err != nil {
			return err
		}
		if !exists {
			if err := facades.Orm().Query().Create(&permission); err != nil {
				return err
			}
		}
	}
	return nil
}

func (m *MfoldersCreateFoldersTable) Down() error {
	for _, permission := range []string{
		"admin.folders.view",
		"admin.folders.create",
		"admin.folders.update",
		"admin.folders.delete",
	} {
		if _, err := facades.Orm().Query().Model(&models.Permission{}).Where("name = ?", permission).Delete(); err != nil {
			return err
		}
	}
	return facades.Schema().DropIfExists("folders")
}
