// Code generated by admin:make-resource. DO NOT EDIT.
package migrations

import (
	"github.com/goravel/framework/contracts/database/schema"

	"goravel/app/facades"
	"goravel/app/models"
)

type MalbumsCreateAlbumsTable struct{}

func (m *MalbumsCreateAlbumsTable) Signature() string {
	return "create_albums_table"
}

func (m *MalbumsCreateAlbumsTable) Up() error {
	if err := facades.Schema().Create("albums", func(table schema.Blueprint) {
		table.ID()
		table.String("name")
		table.Integer("cover_media_id").Nullable()
		table.String("visibility")
		table.Integer("user_id")
		table.DateTimeTz("created_at").Nullable()
		table.DateTimeTz("updated_at").Nullable()
	}); err != nil {
		return err
	}
	for _, permission := range []models.Permission{
		{Name: "admin.albums.view", DisplayName: "Albums.view"},
		{Name: "admin.albums.create", DisplayName: "Albums.create"},
		{Name: "admin.albums.update", DisplayName: "Albums.update"},
		{Name: "admin.albums.delete", DisplayName: "Albums.delete"},
	} {
		exists, err := facades.Orm().Query().Model(&models.Permission{}).Where("name = ?", permission.Name).Exists()
		if err != nil {
			return err
		}
		if !exists {
			if err := facades.Orm().Query().Create(&permission); err != nil {
				return err
			}
		}
	}
	return nil
}

func (m *MalbumsCreateAlbumsTable) Down() error {
	for _, permission := range []string{
		"admin.albums.view",
		"admin.albums.create",
		"admin.albums.update",
		"admin.albums.delete",
	} {
		if _, err := facades.Orm().Query().Model(&models.Permission{}).Where("name = ?", permission).Delete(); err != nil {
			return err
		}
	}
	return facades.Schema().DropIfExists("albums")
}
