// Code generated by admin:make-resource. DO NOT EDIT.
package migrations

import (
	"github.com/goravel/framework/contracts/database/schema"

	"goravel/app/facades"
	"goravel/app/models"
)

type MadvertisingCreateAdvertisingTable struct{}

func (m *MadvertisingCreateAdvertisingTable) Signature() string {
	return "create_advertising_table"
}

func (m *MadvertisingCreateAdvertisingTable) Up() error {
	if err := facades.Schema().Create("advertising", func(table schema.Blueprint) {
		table.ID()
		table.String("name")
		table.String("placement")
		table.String("creative_url")
		table.String("target_url")
		table.String("plan_code")
		table.String("starts_at")
		table.String("ends_at")
		table.String("status")
		table.DateTimeTz("created_at").Nullable()
		table.DateTimeTz("updated_at").Nullable()
	}); err != nil {
		return err
	}
	for _, permission := range []models.Permission{
		{Name: "admin.advertising.view", DisplayName: "Advertising.view"},
		{Name: "admin.advertising.create", DisplayName: "Advertising.create"},
		{Name: "admin.advertising.update", DisplayName: "Advertising.update"},
		{Name: "admin.advertising.delete", DisplayName: "Advertising.delete"},
	} {
		exists, err := facades.Orm().Query().Model(&models.Permission{}).Where("name = ?", permission.Name).Exists()
		if err != nil {
			return err
		}
		if !exists {
			if err := facades.Orm().Query().Create(&permission); err != nil {
				return err
			}
		}
	}
	return nil
}

func (m *MadvertisingCreateAdvertisingTable) Down() error {
	for _, permission := range []string{
		"admin.advertising.view",
		"admin.advertising.create",
		"admin.advertising.update",
		"admin.advertising.delete",
	} {
		if _, err := facades.Orm().Query().Model(&models.Permission{}).Where("name = ?", permission).Delete(); err != nil {
			return err
		}
	}
	return facades.Schema().DropIfExists("advertising")
}
