// Code generated by admin:make-resource. DO NOT EDIT.
package menus

type Entry struct {
	Name       string
	Label      string
	Route      string
	Permission string
	Icon       string
}

var Albums = Entry{Name: "albums", Label: "Albums", Route: "/albums", Permission: "admin.albums.view", Icon: "box"}
