// Code generated by admin:make-resource. DO NOT EDIT.
export const resourceDefinition = {
  name: "folders",
  label: "Folders",
  route: "/folders",
  permission: "admin.folders.view",
  icon: "box",
  pageMode: "generic",
  navigation: { group: "business", order: 100 },
  dataScope: "all",
  ownerField: "user_id",

  actions: [{ name: "view", label: "View", kind: "", permission: "admin.folders.view", batch: false, payload: "" }, { name: "create", label: "Create", kind: "", permission: "admin.folders.create", batch: false, payload: "" }, { name: "update", label: "Update", kind: "", permission: "admin.folders.update", batch: false, payload: "" }, { name: "delete", label: "Delete", kind: "", permission: "admin.folders.delete", batch: false, payload: "" }],
  relations: [],
  form_groups: [],
  details: [],
  fields: [{ name: "name", label: "Name", type: "text", required: true, visible: true, readable: true, writable: true, sensitive: false }, { name: "parent_id", label: "Parent_id", type: "integer", required: false, visible: false, readable: false, writable: false, sensitive: false }, { name: "user_id", label: "User_id", type: "integer", required: false, visible: false, readable: false, writable: false, sensitive: false }],
} as const;
