// Code generated by admin:make-resource. DO NOT EDIT.
package menus

type Entry struct {
	Name       string
	Label      string
	Route      string
	Permission string
	Icon       string
}

var Advertising = Entry{Name: "advertising", Label: "Advertising", Route: "/advertising", Permission: "admin.advertising.view", Icon: "box"}
