// Code generated by admin:make-resource. DO NOT EDIT.
package menus

type Entry struct {
	Name       string
	Label      string
	Route      string
	Permission string
	Icon       string
}

var Folders = Entry{Name: "folders", Label: "Folders", Route: "/folders", Permission: "admin.folders.view", Icon: "box"}
