// Code generated by admin:make-resource. DO NOT EDIT.
package folders

import "goravel/app/core/resource"

func Manifest() resource.Manifest {
	return resource.Manifest{
		Name: "folders", Label: "Folders", Route: "/admin/folders", Table: "folders", Permissions: []string{"admin.folders.view"}, Navigation: resource.Navigation{Group: "business", Order: 100},
		DataScope: resource.DataScopeAll, OwnerField: "user_id",

		Fields: []resource.Field{
			{Name: "name", Label: "Name", Type: "text", Required: true, Visible: true, Readable: true, Writable: true, Sensitive: false, PolicyConfigured: true},
			{Name: "parent_id", Label: "Parent_id", Type: "integer", Required: false, Visible: false, Readable: false, Writable: false, Sensitive: false, PolicyConfigured: true},
			{Name: "user_id", Label: "User_id", Type: "integer", Required: false, Visible: false, Readable: false, Writable: false, Sensitive: false, PolicyConfigured: true},
		},
		Columns: []resource.Column{
			{Name: "name", Label: "Name", Sortable: true},
			{Name: "parent_id", Label: "Parent_id", Sortable: true},
			{Name: "user_id", Label: "User_id", Sortable: true},
		},
		Actions: []resource.Action{
			{Name: "view", Label: "View", Kind: "", Permission: "admin.folders.view", Batch: false, Payload: ""},
			{Name: "create", Label: "Create", Kind: "", Permission: "admin.folders.create", Batch: false, Payload: ""},
			{Name: "update", Label: "Update", Kind: "", Permission: "admin.folders.update", Batch: false, Payload: ""},
			{Name: "delete", Label: "Delete", Kind: "", Permission: "admin.folders.delete", Batch: false, Payload: ""},
		},
		Relations:  []resource.Relation{},
		FormGroups: []resource.FormGroup{},
		Details:    []resource.DetailSection{},
	}
}
