// Code generated by admin:make-resource. DO NOT EDIT.
package folders

import "testing"

func TestManifestHasResourceIdentity(t *testing.T) {
	manifest := Manifest()
	if manifest.Name != "folders" || manifest.Route != "/admin/folders" {
		t.Fatalf("unexpected manifest: %+v", manifest)
	}
	if string(manifest.DataScope) != "all" {
		t.Fatalf("admin folders must be all-scope, got %q", manifest.DataScope)
	}
}
