// Code generated by admin:make-resource. DO NOT EDIT.
package folders

import "github.com/goravel/framework/database/orm"

type Folders struct {
	orm.Model
	Name     string `json:"name"`
	ParentId int    `json:"parent_id"`
	UserId   int    `json:"user_id"`
}
